// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package js

import (
	"github.com/conduitio/conduit-commons/config"
)

func (processorConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		"script": {
			Default:     "",
			Description: "JavaScript code for this processor.\nIt needs to have a function `process()` that accept\na record and returns a record.\nThe `process()` function can either modify the input record and return it,\nor create a new record.\nIf a record needs to be filtered (dropped from the pipeline),\nthen the `process()` function should return a `null`.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		"script.path": {
			Default:     "",
			Description: "The path to a .js file containing the processor code.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
	}
}
