#!/usr/bin/env python3
"""aggregate.py DIR... : one markdown table over staged_session.py outputs."""
import csv, json, os, statistics, sys

def load(d):
    rows = list(csv.DictReader(open(os.path.join(d, "runs.csv"))))
    env = json.load(open(os.path.join(d, "env.json")))
    by = {}
    for r in rows:
        by.setdefault(r["arm"], {"a": {}, "b": {}})[r["rep"]][int(r["round"])] = int(r["rate"])
    return env, by

def fl(by, n):
    ds = []
    for r in by[n]["a"]:
        if r in by[n]["b"] and by[n]["a"][r] and by[n]["b"][r]:
            a, b = by[n]["a"][r], by[n]["b"][r]
            ds.append(abs(b - a) / ((a + b) / 2) * 100)
    return (statistics.median(ds), max(ds)) if ds else (float("nan"), float("nan"))

def med(by, n):
    v = [x for rep in ("a", "b") for x in by[n][rep].values() if x > 0]
    return statistics.median(v) if v else float("nan")

print("# Aggregate of the local sessions\n")
print("Generated by `scripts/aggregate.py`. Local, indicative, not gate evidence; see `README.md`.\n")
print("| session | shape and env | rounds x window | v1 (A/A max) | v2-main (A/A max) | v2-proto (A/A max) | proto vs v1 | proto vs v2-main | v2-main vs v1 |")
print("| --- | --- | --- | --- | --- | --- | --- | --- | --- |")
for d in sys.argv[1:]:
    env, by = load(d)
    m = {n: med(by, n) for n in ("v1", "v2-main", "v2-proto")}
    f = {n: fl(by, n) for n in ("v1", "v2-main", "v2-proto")}
    e = ", ".join(x.replace("CONDUIT_BENCH_", "") for x in env["env"])
    def c(n):
        return f"{m[n]:.0f} (+/-{f[n][1]:.1f}%)"
    def pct(x, y):
        return f"{(m[x]-m[y])/m[y]*100:+.1f}%"
    print(f"| {os.path.basename(d)} | {env['shape']}{' ' + e if e else ''} | {env['rounds']} x {env['window']}s | {c('v1')} | {c('v2-main')} | {c('v2-proto')} | "
          f"{pct('v2-proto','v1')} | {pct('v2-proto','v2-main')} | {pct('v2-main','v1')} |")
