version: 2.0
pipelines:
  - id: test-pipeline-builtin-processor
    status: running
    description: Test pipeline with built-in processor
    connectors:
      - id: generator-source
        type: source
        plugin: builtin:generator
        settings:
          format.type: "structured"
          format.options: "id:int,name:string,company:string,trial:bool"
          recordCount: "3"
      - id: file-destination
        type: destination
        plugin: builtin:file
        settings:
          path: /file_destination.txt
    processors:
      - id: extract-name
        type: extractfieldpayload
        settings:
          field: name
