version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - makezero
    - noctx
    - nolintlint
    - predeclared
    # - revive # TODO enable
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
  settings:
    depguard:
      rules:
        Main:
          deny:
            - pkg: errors
              desc: To accommodate for custom error creation and handling use Conduit's 'cerrors' package instead.
            - pkg: golang.org/x/xerrors
              desc: To accommodate for custom error creation and handling use Conduit's 'cerrors' package instead.
            - pkg: github.com/golang/mock
              desc: github.com/golang/mock is deprecated, use go.uber.org/mock instead.
            - pkg: encoding/json
              desc: github.com/goccy/go-json is preferred for performance reasons.
    gocyclo:
      min-complexity: 20
    goheader:
      values:
        regexp:
          copyright-year: 20[2-9]\d
      template-path: .golangci.goheader.template
    nolintlint:
      allow-unused: false # report any unused nolint directives
      require-explanation: true # require an explanation for nolint directives
      require-specific: true # require nolint directives to mention the specific linter being suppressed
  exclusions:
    generated: lax
    paths:
      - ^examples/
      - ^pkg/plugin/processor/builtin/internal/diff # external code
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goconst
        path: pkg/plugin/processor/builtin/impl
      - linters:
          - staticcheck
        text: "QF1008:" # could remove embedded field from selector
      - linters:
          - dogsled
          - gosec
          - goconst
        path: (.+)_test\.go
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      simplify: false
  exclusions:
    generated: lax
    paths:
      - ^examples/
      - ^pkg/plugin/processor/builtin/internal/diff
