run:
  timeout: 3m
  skip-dirs:
    - /ui/.*

linters-settings:
  depguard:
    rules:
      Main:
        deny:
          - pkg: errors
            desc: To accommodate for custom error creation and handling use Conduit's 'cerrors' package instead.
          - pkg: golang.org/x/xerrors
            desc: To accommodate for custom error creation and handling use Conduit's 'cerrors' package instead.
          - pkg: github.com/golang/mock
            desc: github.com/golang/mock is deprecated, use go.uber.org/mock instead
  gofmt:
    simplify: false
  govet:
    check-shadowing: false # TODO enable
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: true # require nolint directives to mention the specific linter being suppressed
  gocyclo:
    min-complexity: 20
  goconst:
    ignore-tests: true
  goheader:
    template-path: '.golangci.goheader.template'
    values:
      regexp:
        copyright-year: 20[2-9]\d

issues:
  exclude-rules:
    - path: '(.+)acceptance_testing\.go'
      linters:
        - stylecheck
      text: "ST1003: should not use underscores in Go names"
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - dogsled

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    # We plan to enable all of the linters which are commented out.
    # However, we want to enable them one by one (so we don't have to fix many issues at once).
    - bodyclose
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errname
    # - errorlint
    # - exhaustive
    # - exhaustivestruct
    - exportloopref
    # - forbidigo
    # - forcetypeassert
    # - funlen
    # - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    # - cyclop # not interested in package complexities at the moment
    # - godot
    - gofmt
    # - gofumpt
    - goheader
    - goimports
    - revive
    # - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    # - ifshort
    - ineffassign
    # - importas
    # - lll
    # - misspell
    - makezero
    # - nakedret
    # - nilerr
    # - nilnil
    # - nlreturn
    - noctx
    - nolintlint
    # - paralleltest
    - predeclared
    - rowserrcheck
    - staticcheck
    - stylecheck
    - sqlclosecheck
    # - tagliatelle
    # - tenv
    # - thelper
    # - tparallel
    - typecheck
    - unconvert
    # - unparam
    - unused
    - wastedassign
    - whitespace
  # - wrapcheck
  # - wsl

  # don't enable:
  # - asciicheck
  # - dupl
  # - gochecknoglobals
  # - gocognit
  # - godox
  # - goerr113
  # - maligned
  # - nestif
  # - prealloc
  # - testpackage
  # - wsl
