version: 2
builds:
  - main: ./cmd/conduit/main.go
    id: conduit
    binary: conduit
    goos:
      - darwin
      - linux
      - windows
    ignore:
      - goos: windows
        goarch: "386"
    env:
      - CGO_ENABLED=0
    tags:
      - ui
    ldflags:
      - "-s -w -X 'github.com/conduitio/conduit/pkg/conduit.version={{ .Tag }}'"
archives:
  - builds:
      - conduit
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^npm:'
      - '^go.mod:'
      - '^.github:'
      - '^docker:'
      - Merge branch
release:
  prerelease: auto
  mode: append
  footer: |
    ## Release Artifacts

    ### OSX Darwin
    
    - 📦 [conduit_{{ .Version }}_Darwin_arm64.tar.gz](https://conduit.gateway.scarf.sh/conduit/download/{{ .Tag }}/conduit_{{ .Version }}_Darwin_arm64.tar.gz)
    - 📦 [conduit_{{ .Version }}_Darwin_x86_64.tar.gz](https://conduit.gateway.scarf.sh/conduit/download/{{ .Tag }}/conduit_{{ .Version }}_Darwin_x86_64.tar.gz)
    
    ### Linux
    
    - 📦 [conduit_{{ .Version }}_Linux_arm64.deb](https://conduit.gateway.scarf.sh/conduit/download/{{ .Tag }}/conduit_{{ .Version }}_Linux_arm64.deb)
    - 📦 [conduit_{{ .Version }}_Linux_arm64.rpm](https://conduit.gateway.scarf.sh/conduit/download/{{ .Tag }}/conduit_{{ .Version }}_Linux_arm64.rpm)
    - 📦 [conduit_{{ .Version }}_Linux_arm64.tar.gz](https://conduit.gateway.scarf.sh/conduit/download/{{ .Tag }}/conduit_{{ .Version }}_Linux_arm64.tar.gz)
    - 📦 [conduit_{{ .Version }}_Linux_i386.deb](https://conduit.gateway.scarf.sh/conduit/download/{{ .Tag }}/conduit_{{ .Version }}_Linux_i386.deb)
    - 📦 [conduit_{{ .Version }}_Linux_i386.rpm](https://conduit.gateway.scarf.sh/conduit/download/{{ .Tag }}/conduit_{{ .Version }}_Linux_i386.rpm)
    - 📦 [conduit_{{ .Version }}_Linux_i386.tar.gz](https://conduit.gateway.scarf.sh/conduit/download/{{ .Tag }}/conduit_{{ .Version }}_Linux_i386.tar.gz)
    - 📦 [conduit_{{ .Version }}_Linux_x86_64.deb](https://conduit.gateway.scarf.sh/conduit/download/{{ .Tag }}/conduit_{{ .Version }}_Linux_x86_64.deb)
    - 📦 [conduit_{{ .Version }}_Linux_x86_64.rpm](https://conduit.gateway.scarf.sh/conduit/download/{{ .Tag }}/conduit_{{ .Version }}_Linux_x86_64.rpm)
    - 📦 [conduit_{{ .Version }}_Linux_x86_64.tar.gz](https://conduit.gateway.scarf.sh/conduit/download/{{ .Tag }}/conduit_{{ .Version }}_Linux_x86_64.tar.gz)
    
    ### Windows
    
    - 📦 [conduit_{{ .Version }}_Windows_arm64.zip](https://conduit.gateway.scarf.sh/conduit/download/{{ .Tag }}/conduit_{{ .Version }}_Windows_arm64.zip)
    - 📦 [conduit_{{ .Version }}_Windows_x86_64.zip](https://conduit.gateway.scarf.sh/conduit/download/{{ .Tag }}/conduit_{{ .Version }}_Windows_x86_64.zip)

    ## Docker images

    To pull the image, you can execute the following command:
    ```
    docker pull conduit.docker.scarf.sh/conduitio/conduit:{{ .Tag }}
    ```
    ![conduit-release-view](https://static.scarf.sh/a.png?x-pxid=3df89eef-1623-4cd5-9dbc-a6b36588a0eb)
nfpms:
  - license: Apache-2.0
    maintainer: Conduit Developers <conduit-dev@meroxa.io>
    homepage: https://conduit.io/
    description: "Conduit streams data between data stores. Kafka Connect replacement. No JVM required."
    section: utils
    formats:
      - rpm
      - deb
    file_name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
