before:
  hooks:
    - make ui-dist
builds:
  - main: ./cmd/conduit/main.go
    id: conduit
    binary: conduit
    goos:
      - linux
    env:
      - CGO_ENABLED=0
    tags:
      - ui
  # The S3 plugin
  - main: pkg/plugins/s3/cmd/s3/main.go
    id: s3
    binary: pkg/plugins/s3/s3
    goos:
      - linux
    env:
      - CGO_ENABLED=0
  # The Postgres plugin
  - main: pkg/plugins/pg/cmd/pg/main.go
    id: pg
    binary: pkg/plugins/pg/pg
    goos:
      - linux
    env:
      - CGO_ENABLED=0
  # The file plugin
  - main: pkg/plugins/file/cmd/file/main.go
    id: file
    binary: pkg/plugins/file/file
    goos:
      - linux
    env:
      - CGO_ENABLED=0
  # The generator plugin
  - main: pkg/plugins/generator/cmd/generator/main.go
    id: generator
    binary: pkg/plugins/generator/generator
    goos:
      - linux
    env:
      - CGO_ENABLED=0
  # The Kafka plugin
  - main: pkg/plugins/kafka/cmd/kafka/main.go
    id: kafka
    binary: pkg/plugins/kafka/kafka
    env:
      - CGO_ENABLED=1
    targets:
      - linux_amd64
archives:
  - builds:
      - conduit
      - s3
      - pg
      - file
      - generator
      - kafka
    allow_different_binary_count: true
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums_linux.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^npm:'
      - '^go.mod:'
      - Merge branch
release:
  mode: append
  footer: |
    ## Docker images

    To pull the image, you can execute the following command:
    ```
    docker pull ghcr.io/conduitio/conduit:{{ .Tag }}
    ```
