before:
  hooks:
    - make ui-dist
builds:
  - main: ./cmd/conduit/main.go
    id: conduit
    binary: conduit
    goos:
      - darwin
      - linux
      - windows
    env:
      - CGO_ENABLED=0
    tags:
      - ui
    ldflags:
      - "-s -w -X 'github.com/conduitio/conduit/pkg/conduit.version={{ .Tag }}'"
archives:
  - builds:
      - conduit
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^npm:'
      - '^go.mod:'
      - '^.github:'
      - Merge branch
release:
  prerelease: auto
  mode: append
  footer: |
    ## Docker images

    To pull the image, you can execute the following command:
    ```
    docker pull ghcr.io/conduitio/conduit:{{ .Tag }}
    ```
