// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package cohere

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	CommandProcessorConfigApiKey             = "apiKey"
	CommandProcessorConfigBackoffRetryCount  = "backoffRetry.count"
	CommandProcessorConfigBackoffRetryFactor = "backoffRetry.factor"
	CommandProcessorConfigBackoffRetryMax    = "backoffRetry.max"
	CommandProcessorConfigBackoffRetryMin    = "backoffRetry.min"
	CommandProcessorConfigModel              = "model"
	CommandProcessorConfigResponseBody       = "response.body"
)

func (CommandProcessorConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		CommandProcessorConfigApiKey: {
			Default:     "",
			Description: "APIKey is the API key for Cohere api calls.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		CommandProcessorConfigBackoffRetryCount: {
			Default:     "0",
			Description: "Maximum number of retries for an individual record when backing off following an error.",
			Type:        config.ParameterTypeFloat,
			Validations: []config.Validation{
				config.ValidationGreaterThan{V: -1},
			},
		},
		CommandProcessorConfigBackoffRetryFactor: {
			Default:     "2",
			Description: "The multiplying factor for each increment step.",
			Type:        config.ParameterTypeFloat,
			Validations: []config.Validation{
				config.ValidationGreaterThan{V: 0},
			},
		},
		CommandProcessorConfigBackoffRetryMax: {
			Default:     "5s",
			Description: "The maximum waiting time before retrying.",
			Type:        config.ParameterTypeDuration,
			Validations: []config.Validation{},
		},
		CommandProcessorConfigBackoffRetryMin: {
			Default:     "100ms",
			Description: "The minimum waiting time before retrying.",
			Type:        config.ParameterTypeDuration,
			Validations: []config.Validation{},
		},
		CommandProcessorConfigModel: {
			Default:     "command",
			Description: "Model is one of the Cohere model (command,embed,rerank).",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		CommandProcessorConfigResponseBody: {
			Default:     ".Payload.After",
			Description: "Specifies in which field should the response body be saved.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
	}
}
