// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package ollama

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	requestProcessorConfigModel  = "model"
	requestProcessorConfigPrompt = "prompt"
	requestProcessorConfigUrl    = "url"
)

func (requestProcessorConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		requestProcessorConfigModel: {
			Default:     "llama3.2",
			Description: "Model is the name of the model used with ollama",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		requestProcessorConfigPrompt: {
			Default:     "",
			Description: "Prompt is the prompt to pass into ollama to tranform the data",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		requestProcessorConfigUrl: {
			Default:     "",
			Description: "OllamaURL is the url to the ollama instance",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
