// Copyright © 2026 Meroxa, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package storecompat is the upgrade gate for the embedded storage engines
// that hold Conduit's durable state: pipeline instances (with their status,
// error and DLQ configuration), connector instances (with source positions
// and destination ack positions) and processor instances.
//
// The badger and SQLite libraries reach conduit transitively (through
// conduit-commons), so their versions move whenever a dependency bump
// happens to raise them. Nothing pins them to their on-disk format. This
// package keeps a database written by an older library version in
// testdata/ and requires that the current build can:
//
//  1. open it,
//  2. read every instance back through the real stores (pipeline.Store,
//     connector.Store, processor.Store) and get exactly what was written,
//  3. resume: persist a newer source position through connector.Persister
//     (the same path a running source uses), close, reopen, and read the
//     newer position back with everything else unchanged.
//
// Invariant 2 (positions are monotonic and crash-safe across restarts) and
// the backward-compatibility rule (serialized state must stay readable by
// N+1) are what this enforces for the storage engine itself.
//
// Fixtures are generated by internal/gen, built from this package's code
// but with the storage libraries pinned to the old versions through a
// temporary modfile (see internal/gen's package doc for the exact
// command). Each fixture directory carries a manifest.json recording the
// library versions that wrote it, and the test checks the manifest so a
// fixture regenerated by the wrong build fails loudly instead of quietly
// testing nothing.
//
// The fixtures are never modified in place: each test copies its fixture
// into t.TempDir() first.
package storecompat
