// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/conduitio/conduit/pkg/processor (interfaces: PluginRegistry)
//
// Generated by this command:
//
//	mockgen -destination=mock/processor_registry.go -package=mock -mock_names=PluginRegistry=PluginRegistry . PluginRegistry
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	sdk "github.com/conduitio/conduit-processor-sdk"
	gomock "go.uber.org/mock/gomock"
)

// PluginRegistry is a mock of PluginRegistry interface.
type PluginRegistry struct {
	ctrl     *gomock.Controller
	recorder *PluginRegistryMockRecorder
}

// PluginRegistryMockRecorder is the mock recorder for PluginRegistry.
type PluginRegistryMockRecorder struct {
	mock *PluginRegistry
}

// NewPluginRegistry creates a new mock instance.
func NewPluginRegistry(ctrl *gomock.Controller) *PluginRegistry {
	mock := &PluginRegistry{ctrl: ctrl}
	mock.recorder = &PluginRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *PluginRegistry) EXPECT() *PluginRegistryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *PluginRegistry) Get(arg0 context.Context, arg1, arg2 string) (sdk.Processor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(sdk.Processor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *PluginRegistryMockRecorder) Get(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*PluginRegistry)(nil).Get), arg0, arg1, arg2)
}
