// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package openai

import (
	"regexp"

	"github.com/conduitio/conduit-commons/config"
)

const (
	embeddingProcConfigApiKey     = "apiKey"
	embeddingProcConfigEndpoint   = "endpoint"
	embeddingProcConfigInputField = "inputField"
	embeddingProcConfigModel      = "model"
)

func (embeddingProcConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		embeddingProcConfigApiKey: {
			Default:     "",
			Description: "",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		embeddingProcConfigEndpoint: {
			Default:     "https://api.openai.com/v1",
			Description: "",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		embeddingProcConfigInputField: {
			Default:     ".Payload.After",
			Description: "",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRegex{Regex: regexp.MustCompile("^\\.(Payload|Key).*")},
			},
		},
		embeddingProcConfigModel: {
			Default:     "",
			Description: "",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
				config.ValidationInclusion{List: []string{"gpt-4", "gpt-4-turbo", "gpt-3.5-turbo", "text-davinci-003", "text-davinci-002", "text-curie-001", "text-babbage-001", "text-ada-001"}},
			},
		},
	}
}
