name: 🐛 Bug
description: Report a bug.
title: "Bug: <title>"
labels: [bug, triage]
body:
- type: textarea
  attributes:
    label: Bug description
    description: A concise description of what you're experiencing and what you expected to happen instead.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this Conduit configuration...
      3. And this pipeline configuration file...
      4. Run '...'
      5. See error...
  validations:
    required: true
- type: input
  attributes:
    label: Version
    description: "Conduit version, OS, Arch (hint: get it with `conduit --version` or through the HTTP API `GET /info`)."
    placeholder: v0.3.0 darwin/amd64
  validations:
    required: true
