// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/conduitio/conduit/pkg/web/api (interfaces: ProcessorOrchestrator)
//
// Generated by this command:
//
//	mockgen -typed -destination=mock/processor.go -package=mock -mock_names=ProcessorOrchestrator=ProcessorOrchestrator . ProcessorOrchestrator
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	inspector "github.com/conduitio/conduit/pkg/inspector"
	processor "github.com/conduitio/conduit/pkg/processor"
	gomock "go.uber.org/mock/gomock"
)

// ProcessorOrchestrator is a mock of ProcessorOrchestrator interface.
type ProcessorOrchestrator struct {
	ctrl     *gomock.Controller
	recorder *ProcessorOrchestratorMockRecorder
	isgomock struct{}
}

// ProcessorOrchestratorMockRecorder is the mock recorder for ProcessorOrchestrator.
type ProcessorOrchestratorMockRecorder struct {
	mock *ProcessorOrchestrator
}

// NewProcessorOrchestrator creates a new mock instance.
func NewProcessorOrchestrator(ctrl *gomock.Controller) *ProcessorOrchestrator {
	mock := &ProcessorOrchestrator{ctrl: ctrl}
	mock.recorder = &ProcessorOrchestratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ProcessorOrchestrator) EXPECT() *ProcessorOrchestratorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *ProcessorOrchestrator) Create(ctx context.Context, procType string, parent processor.Parent, cfg processor.Config, condition string) (*processor.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, procType, parent, cfg, condition)
	ret0, _ := ret[0].(*processor.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *ProcessorOrchestratorMockRecorder) Create(ctx, procType, parent, cfg, condition any) *ProcessorOrchestratorCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*ProcessorOrchestrator)(nil).Create), ctx, procType, parent, cfg, condition)
	return &ProcessorOrchestratorCreateCall{Call: call}
}

// ProcessorOrchestratorCreateCall wrap *gomock.Call
type ProcessorOrchestratorCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ProcessorOrchestratorCreateCall) Return(arg0 *processor.Instance, arg1 error) *ProcessorOrchestratorCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ProcessorOrchestratorCreateCall) Do(f func(context.Context, string, processor.Parent, processor.Config, string) (*processor.Instance, error)) *ProcessorOrchestratorCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ProcessorOrchestratorCreateCall) DoAndReturn(f func(context.Context, string, processor.Parent, processor.Config, string) (*processor.Instance, error)) *ProcessorOrchestratorCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *ProcessorOrchestrator) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *ProcessorOrchestratorMockRecorder) Delete(ctx, id any) *ProcessorOrchestratorDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*ProcessorOrchestrator)(nil).Delete), ctx, id)
	return &ProcessorOrchestratorDeleteCall{Call: call}
}

// ProcessorOrchestratorDeleteCall wrap *gomock.Call
type ProcessorOrchestratorDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ProcessorOrchestratorDeleteCall) Return(arg0 error) *ProcessorOrchestratorDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ProcessorOrchestratorDeleteCall) Do(f func(context.Context, string) error) *ProcessorOrchestratorDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ProcessorOrchestratorDeleteCall) DoAndReturn(f func(context.Context, string) error) *ProcessorOrchestratorDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *ProcessorOrchestrator) Get(ctx context.Context, id string) (*processor.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*processor.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *ProcessorOrchestratorMockRecorder) Get(ctx, id any) *ProcessorOrchestratorGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*ProcessorOrchestrator)(nil).Get), ctx, id)
	return &ProcessorOrchestratorGetCall{Call: call}
}

// ProcessorOrchestratorGetCall wrap *gomock.Call
type ProcessorOrchestratorGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ProcessorOrchestratorGetCall) Return(arg0 *processor.Instance, arg1 error) *ProcessorOrchestratorGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ProcessorOrchestratorGetCall) Do(f func(context.Context, string) (*processor.Instance, error)) *ProcessorOrchestratorGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ProcessorOrchestratorGetCall) DoAndReturn(f func(context.Context, string) (*processor.Instance, error)) *ProcessorOrchestratorGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// InspectIn mocks base method.
func (m *ProcessorOrchestrator) InspectIn(ctx context.Context, id string) (*inspector.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InspectIn", ctx, id)
	ret0, _ := ret[0].(*inspector.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InspectIn indicates an expected call of InspectIn.
func (mr *ProcessorOrchestratorMockRecorder) InspectIn(ctx, id any) *ProcessorOrchestratorInspectInCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InspectIn", reflect.TypeOf((*ProcessorOrchestrator)(nil).InspectIn), ctx, id)
	return &ProcessorOrchestratorInspectInCall{Call: call}
}

// ProcessorOrchestratorInspectInCall wrap *gomock.Call
type ProcessorOrchestratorInspectInCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ProcessorOrchestratorInspectInCall) Return(arg0 *inspector.Session, arg1 error) *ProcessorOrchestratorInspectInCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ProcessorOrchestratorInspectInCall) Do(f func(context.Context, string) (*inspector.Session, error)) *ProcessorOrchestratorInspectInCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ProcessorOrchestratorInspectInCall) DoAndReturn(f func(context.Context, string) (*inspector.Session, error)) *ProcessorOrchestratorInspectInCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// InspectOut mocks base method.
func (m *ProcessorOrchestrator) InspectOut(ctx context.Context, id string) (*inspector.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InspectOut", ctx, id)
	ret0, _ := ret[0].(*inspector.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InspectOut indicates an expected call of InspectOut.
func (mr *ProcessorOrchestratorMockRecorder) InspectOut(ctx, id any) *ProcessorOrchestratorInspectOutCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InspectOut", reflect.TypeOf((*ProcessorOrchestrator)(nil).InspectOut), ctx, id)
	return &ProcessorOrchestratorInspectOutCall{Call: call}
}

// ProcessorOrchestratorInspectOutCall wrap *gomock.Call
type ProcessorOrchestratorInspectOutCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ProcessorOrchestratorInspectOutCall) Return(arg0 *inspector.Session, arg1 error) *ProcessorOrchestratorInspectOutCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ProcessorOrchestratorInspectOutCall) Do(f func(context.Context, string) (*inspector.Session, error)) *ProcessorOrchestratorInspectOutCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ProcessorOrchestratorInspectOutCall) DoAndReturn(f func(context.Context, string) (*inspector.Session, error)) *ProcessorOrchestratorInspectOutCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *ProcessorOrchestrator) List(ctx context.Context) map[string]*processor.Instance {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].(map[string]*processor.Instance)
	return ret0
}

// List indicates an expected call of List.
func (mr *ProcessorOrchestratorMockRecorder) List(ctx any) *ProcessorOrchestratorListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*ProcessorOrchestrator)(nil).List), ctx)
	return &ProcessorOrchestratorListCall{Call: call}
}

// ProcessorOrchestratorListCall wrap *gomock.Call
type ProcessorOrchestratorListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ProcessorOrchestratorListCall) Return(arg0 map[string]*processor.Instance) *ProcessorOrchestratorListCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ProcessorOrchestratorListCall) Do(f func(context.Context) map[string]*processor.Instance) *ProcessorOrchestratorListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ProcessorOrchestratorListCall) DoAndReturn(f func(context.Context) map[string]*processor.Instance) *ProcessorOrchestratorListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *ProcessorOrchestrator) Update(ctx context.Context, id, plugin string, cfg processor.Config) (*processor.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, plugin, cfg)
	ret0, _ := ret[0].(*processor.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *ProcessorOrchestratorMockRecorder) Update(ctx, id, plugin, cfg any) *ProcessorOrchestratorUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*ProcessorOrchestrator)(nil).Update), ctx, id, plugin, cfg)
	return &ProcessorOrchestratorUpdateCall{Call: call}
}

// ProcessorOrchestratorUpdateCall wrap *gomock.Call
type ProcessorOrchestratorUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ProcessorOrchestratorUpdateCall) Return(arg0 *processor.Instance, arg1 error) *ProcessorOrchestratorUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ProcessorOrchestratorUpdateCall) Do(f func(context.Context, string, string, processor.Config) (*processor.Instance, error)) *ProcessorOrchestratorUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ProcessorOrchestratorUpdateCall) DoAndReturn(f func(context.Context, string, string, processor.Config) (*processor.Instance, error)) *ProcessorOrchestratorUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
