// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package field

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	renameConfigMapping = "mapping"
)

func (renameConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		renameConfigMapping: {
			Default:     "",
			Description: "Mapping is a comma separated list of keys and values for fields and their\nnew names (keys and values are separated by colons \":\").\n\nFor example: `.Metadata.key:id,.Payload.After.foo:bar`.\n\nFor more information about the format, see [Referencing fields](https://conduit.io/docs/using/processors/referencing-fields).",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
