// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/conduitio/conduit/pkg/provisioning (interfaces: PipelineService,ConnectorService,ProcessorService,ConnectorPluginService)
//
// Generated by this command:
//
//	mockgen -typed -destination=mock/provisioning.go -package=mock -mock_names=PipelineService=PipelineService,ConnectorService=ConnectorService,ProcessorService=ProcessorService,ConnectorPluginService=ConnectorPluginService . PipelineService,ConnectorService,ProcessorService,ConnectorPluginService
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	connector "github.com/conduitio/conduit/pkg/connector"
	log "github.com/conduitio/conduit/pkg/foundation/log"
	"github.com/conduitio/conduit/pkg/lifecycle"
	pipeline "github.com/conduitio/conduit/pkg/pipeline"
	connector0 "github.com/conduitio/conduit/pkg/plugin/connector"
	processor "github.com/conduitio/conduit/pkg/processor"
	gomock "go.uber.org/mock/gomock"
)

// PipelineService is a mock of PipelineService interface.
type PipelineService struct {
	ctrl     *gomock.Controller
	recorder *PipelineServiceMockRecorder
}

// PipelineServiceMockRecorder is the mock recorder for PipelineService.
type PipelineServiceMockRecorder struct {
	mock *PipelineService
}

// NewPipelineService creates a new mock instance.
func NewPipelineService(ctrl *gomock.Controller) *PipelineService {
	mock := &PipelineService{ctrl: ctrl}
	mock.recorder = &PipelineServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *PipelineService) EXPECT() *PipelineServiceMockRecorder {
	return m.recorder
}

// AddConnector mocks base method.
func (m *PipelineService) AddConnector(arg0 context.Context, arg1, arg2 string) (*pipeline.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddConnector", arg0, arg1, arg2)
	ret0, _ := ret[0].(*pipeline.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddConnector indicates an expected call of AddConnector.
func (mr *PipelineServiceMockRecorder) AddConnector(arg0, arg1, arg2 any) *PipelineServiceAddConnectorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddConnector", reflect.TypeOf((*PipelineService)(nil).AddConnector), arg0, arg1, arg2)
	return &PipelineServiceAddConnectorCall{Call: call}
}

// PipelineServiceAddConnectorCall wrap *gomock.Call
type PipelineServiceAddConnectorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *PipelineServiceAddConnectorCall) Return(arg0 *pipeline.Instance, arg1 error) *PipelineServiceAddConnectorCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *PipelineServiceAddConnectorCall) Do(f func(context.Context, string, string) (*pipeline.Instance, error)) *PipelineServiceAddConnectorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *PipelineServiceAddConnectorCall) DoAndReturn(f func(context.Context, string, string) (*pipeline.Instance, error)) *PipelineServiceAddConnectorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddProcessor mocks base method.
func (m *PipelineService) AddProcessor(arg0 context.Context, arg1, arg2 string) (*pipeline.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProcessor", arg0, arg1, arg2)
	ret0, _ := ret[0].(*pipeline.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddProcessor indicates an expected call of AddProcessor.
func (mr *PipelineServiceMockRecorder) AddProcessor(arg0, arg1, arg2 any) *PipelineServiceAddProcessorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProcessor", reflect.TypeOf((*PipelineService)(nil).AddProcessor), arg0, arg1, arg2)
	return &PipelineServiceAddProcessorCall{Call: call}
}

// PipelineServiceAddProcessorCall wrap *gomock.Call
type PipelineServiceAddProcessorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *PipelineServiceAddProcessorCall) Return(arg0 *pipeline.Instance, arg1 error) *PipelineServiceAddProcessorCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *PipelineServiceAddProcessorCall) Do(f func(context.Context, string, string) (*pipeline.Instance, error)) *PipelineServiceAddProcessorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *PipelineServiceAddProcessorCall) DoAndReturn(f func(context.Context, string, string) (*pipeline.Instance, error)) *PipelineServiceAddProcessorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *PipelineService) Create(arg0 context.Context, arg1 string, arg2 pipeline.Config, arg3 pipeline.ProvisionType) (*pipeline.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*pipeline.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *PipelineServiceMockRecorder) Create(arg0, arg1, arg2, arg3 any) *PipelineServiceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*PipelineService)(nil).Create), arg0, arg1, arg2, arg3)
	return &PipelineServiceCreateCall{Call: call}
}

// PipelineServiceCreateCall wrap *gomock.Call
type PipelineServiceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *PipelineServiceCreateCall) Return(arg0 *pipeline.Instance, arg1 error) *PipelineServiceCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *PipelineServiceCreateCall) Do(f func(context.Context, string, pipeline.Config, pipeline.ProvisionType) (*pipeline.Instance, error)) *PipelineServiceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *PipelineServiceCreateCall) DoAndReturn(f func(context.Context, string, pipeline.Config, pipeline.ProvisionType) (*pipeline.Instance, error)) *PipelineServiceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *PipelineService) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *PipelineServiceMockRecorder) Delete(arg0, arg1 any) *PipelineServiceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*PipelineService)(nil).Delete), arg0, arg1)
	return &PipelineServiceDeleteCall{Call: call}
}

// PipelineServiceDeleteCall wrap *gomock.Call
type PipelineServiceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *PipelineServiceDeleteCall) Return(arg0 error) *PipelineServiceDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *PipelineServiceDeleteCall) Do(f func(context.Context, string) error) *PipelineServiceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *PipelineServiceDeleteCall) DoAndReturn(f func(context.Context, string) error) *PipelineServiceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *PipelineService) Get(arg0 context.Context, arg1 string) (*pipeline.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*pipeline.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *PipelineServiceMockRecorder) Get(arg0, arg1 any) *PipelineServiceGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*PipelineService)(nil).Get), arg0, arg1)
	return &PipelineServiceGetCall{Call: call}
}

// PipelineServiceGetCall wrap *gomock.Call
type PipelineServiceGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *PipelineServiceGetCall) Return(arg0 *pipeline.Instance, arg1 error) *PipelineServiceGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *PipelineServiceGetCall) Do(f func(context.Context, string) (*pipeline.Instance, error)) *PipelineServiceGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *PipelineServiceGetCall) DoAndReturn(f func(context.Context, string) (*pipeline.Instance, error)) *PipelineServiceGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *PipelineService) List(arg0 context.Context) map[string]*pipeline.Instance {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].(map[string]*pipeline.Instance)
	return ret0
}

// List indicates an expected call of List.
func (mr *PipelineServiceMockRecorder) List(arg0 any) *PipelineServiceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*PipelineService)(nil).List), arg0)
	return &PipelineServiceListCall{Call: call}
}

// PipelineServiceListCall wrap *gomock.Call
type PipelineServiceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *PipelineServiceListCall) Return(arg0 map[string]*pipeline.Instance) *PipelineServiceListCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *PipelineServiceListCall) Do(f func(context.Context) map[string]*pipeline.Instance) *PipelineServiceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *PipelineServiceListCall) DoAndReturn(f func(context.Context) map[string]*pipeline.Instance) *PipelineServiceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemoveConnector mocks base method.
func (m *PipelineService) RemoveConnector(arg0 context.Context, arg1, arg2 string) (*pipeline.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveConnector", arg0, arg1, arg2)
	ret0, _ := ret[0].(*pipeline.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveConnector indicates an expected call of RemoveConnector.
func (mr *PipelineServiceMockRecorder) RemoveConnector(arg0, arg1, arg2 any) *PipelineServiceRemoveConnectorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveConnector", reflect.TypeOf((*PipelineService)(nil).RemoveConnector), arg0, arg1, arg2)
	return &PipelineServiceRemoveConnectorCall{Call: call}
}

// PipelineServiceRemoveConnectorCall wrap *gomock.Call
type PipelineServiceRemoveConnectorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *PipelineServiceRemoveConnectorCall) Return(arg0 *pipeline.Instance, arg1 error) *PipelineServiceRemoveConnectorCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *PipelineServiceRemoveConnectorCall) Do(f func(context.Context, string, string) (*pipeline.Instance, error)) *PipelineServiceRemoveConnectorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *PipelineServiceRemoveConnectorCall) DoAndReturn(f func(context.Context, string, string) (*pipeline.Instance, error)) *PipelineServiceRemoveConnectorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemoveProcessor mocks base method.
func (m *PipelineService) RemoveProcessor(arg0 context.Context, arg1, arg2 string) (*pipeline.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveProcessor", arg0, arg1, arg2)
	ret0, _ := ret[0].(*pipeline.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveProcessor indicates an expected call of RemoveProcessor.
func (mr *PipelineServiceMockRecorder) RemoveProcessor(arg0, arg1, arg2 any) *PipelineServiceRemoveProcessorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveProcessor", reflect.TypeOf((*PipelineService)(nil).RemoveProcessor), arg0, arg1, arg2)
	return &PipelineServiceRemoveProcessorCall{Call: call}
}

// PipelineServiceRemoveProcessorCall wrap *gomock.Call
type PipelineServiceRemoveProcessorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *PipelineServiceRemoveProcessorCall) Return(arg0 *pipeline.Instance, arg1 error) *PipelineServiceRemoveProcessorCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *PipelineServiceRemoveProcessorCall) Do(f func(context.Context, string, string) (*pipeline.Instance, error)) *PipelineServiceRemoveProcessorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *PipelineServiceRemoveProcessorCall) DoAndReturn(f func(context.Context, string, string) (*pipeline.Instance, error)) *PipelineServiceRemoveProcessorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Start mocks base method.
func (m *PipelineService) Start(arg0 context.Context, arg1 lifecycle.ConnectorFetcher, arg2 lifecycle.ProcessorService, arg3 lifecycle.PluginDispenserFetcher, arg4 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *PipelineServiceMockRecorder) Start(arg0, arg1, arg2, arg3, arg4 any) *PipelineServiceStartCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*PipelineService)(nil).Start), arg0, arg1, arg2, arg3, arg4)
	return &PipelineServiceStartCall{Call: call}
}

// PipelineServiceStartCall wrap *gomock.Call
type PipelineServiceStartCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *PipelineServiceStartCall) Return(arg0 error) *PipelineServiceStartCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *PipelineServiceStartCall) Do(f func(context.Context, lifecycle.ConnectorFetcher, lifecycle.ProcessorService, lifecycle.PluginDispenserFetcher, string) error) *PipelineServiceStartCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *PipelineServiceStartCall) DoAndReturn(f func(context.Context, lifecycle.ConnectorFetcher, lifecycle.ProcessorService, lifecycle.PluginDispenserFetcher, string) error) *PipelineServiceStartCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Stop mocks base method.
func (m *PipelineService) Stop(arg0 context.Context, arg1 string, arg2 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *PipelineServiceMockRecorder) Stop(arg0, arg1, arg2 any) *PipelineServiceStopCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*PipelineService)(nil).Stop), arg0, arg1, arg2)
	return &PipelineServiceStopCall{Call: call}
}

// PipelineServiceStopCall wrap *gomock.Call
type PipelineServiceStopCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *PipelineServiceStopCall) Return(arg0 error) *PipelineServiceStopCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *PipelineServiceStopCall) Do(f func(context.Context, string, bool) error) *PipelineServiceStopCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *PipelineServiceStopCall) DoAndReturn(f func(context.Context, string, bool) error) *PipelineServiceStopCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *PipelineService) Update(arg0 context.Context, arg1 string, arg2 pipeline.Config) (*pipeline.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*pipeline.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *PipelineServiceMockRecorder) Update(arg0, arg1, arg2 any) *PipelineServiceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*PipelineService)(nil).Update), arg0, arg1, arg2)
	return &PipelineServiceUpdateCall{Call: call}
}

// PipelineServiceUpdateCall wrap *gomock.Call
type PipelineServiceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *PipelineServiceUpdateCall) Return(arg0 *pipeline.Instance, arg1 error) *PipelineServiceUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *PipelineServiceUpdateCall) Do(f func(context.Context, string, pipeline.Config) (*pipeline.Instance, error)) *PipelineServiceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *PipelineServiceUpdateCall) DoAndReturn(f func(context.Context, string, pipeline.Config) (*pipeline.Instance, error)) *PipelineServiceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateDLQ mocks base method.
func (m *PipelineService) UpdateDLQ(arg0 context.Context, arg1 string, arg2 pipeline.DLQ) (*pipeline.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDLQ", arg0, arg1, arg2)
	ret0, _ := ret[0].(*pipeline.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDLQ indicates an expected call of UpdateDLQ.
func (mr *PipelineServiceMockRecorder) UpdateDLQ(arg0, arg1, arg2 any) *PipelineServiceUpdateDLQCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDLQ", reflect.TypeOf((*PipelineService)(nil).UpdateDLQ), arg0, arg1, arg2)
	return &PipelineServiceUpdateDLQCall{Call: call}
}

// PipelineServiceUpdateDLQCall wrap *gomock.Call
type PipelineServiceUpdateDLQCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *PipelineServiceUpdateDLQCall) Return(arg0 *pipeline.Instance, arg1 error) *PipelineServiceUpdateDLQCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *PipelineServiceUpdateDLQCall) Do(f func(context.Context, string, pipeline.DLQ) (*pipeline.Instance, error)) *PipelineServiceUpdateDLQCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *PipelineServiceUpdateDLQCall) DoAndReturn(f func(context.Context, string, pipeline.DLQ) (*pipeline.Instance, error)) *PipelineServiceUpdateDLQCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ConnectorService is a mock of ConnectorService interface.
type ConnectorService struct {
	ctrl     *gomock.Controller
	recorder *ConnectorServiceMockRecorder
}

// ConnectorServiceMockRecorder is the mock recorder for ConnectorService.
type ConnectorServiceMockRecorder struct {
	mock *ConnectorService
}

// NewConnectorService creates a new mock instance.
func NewConnectorService(ctrl *gomock.Controller) *ConnectorService {
	mock := &ConnectorService{ctrl: ctrl}
	mock.recorder = &ConnectorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ConnectorService) EXPECT() *ConnectorServiceMockRecorder {
	return m.recorder
}

// AddProcessor mocks base method.
func (m *ConnectorService) AddProcessor(arg0 context.Context, arg1, arg2 string) (*connector.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProcessor", arg0, arg1, arg2)
	ret0, _ := ret[0].(*connector.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddProcessor indicates an expected call of AddProcessor.
func (mr *ConnectorServiceMockRecorder) AddProcessor(arg0, arg1, arg2 any) *ConnectorServiceAddProcessorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProcessor", reflect.TypeOf((*ConnectorService)(nil).AddProcessor), arg0, arg1, arg2)
	return &ConnectorServiceAddProcessorCall{Call: call}
}

// ConnectorServiceAddProcessorCall wrap *gomock.Call
type ConnectorServiceAddProcessorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ConnectorServiceAddProcessorCall) Return(arg0 *connector.Instance, arg1 error) *ConnectorServiceAddProcessorCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ConnectorServiceAddProcessorCall) Do(f func(context.Context, string, string) (*connector.Instance, error)) *ConnectorServiceAddProcessorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ConnectorServiceAddProcessorCall) DoAndReturn(f func(context.Context, string, string) (*connector.Instance, error)) *ConnectorServiceAddProcessorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *ConnectorService) Create(arg0 context.Context, arg1 string, arg2 connector.Type, arg3, arg4 string, arg5 connector.Config, arg6 connector.ProvisionType) (*connector.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(*connector.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *ConnectorServiceMockRecorder) Create(arg0, arg1, arg2, arg3, arg4, arg5, arg6 any) *ConnectorServiceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*ConnectorService)(nil).Create), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	return &ConnectorServiceCreateCall{Call: call}
}

// ConnectorServiceCreateCall wrap *gomock.Call
type ConnectorServiceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ConnectorServiceCreateCall) Return(arg0 *connector.Instance, arg1 error) *ConnectorServiceCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ConnectorServiceCreateCall) Do(f func(context.Context, string, connector.Type, string, string, connector.Config, connector.ProvisionType) (*connector.Instance, error)) *ConnectorServiceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ConnectorServiceCreateCall) DoAndReturn(f func(context.Context, string, connector.Type, string, string, connector.Config, connector.ProvisionType) (*connector.Instance, error)) *ConnectorServiceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *ConnectorService) Delete(arg0 context.Context, arg1 string, arg2 connector.PluginDispenserFetcher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *ConnectorServiceMockRecorder) Delete(arg0, arg1, arg2 any) *ConnectorServiceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*ConnectorService)(nil).Delete), arg0, arg1, arg2)
	return &ConnectorServiceDeleteCall{Call: call}
}

// ConnectorServiceDeleteCall wrap *gomock.Call
type ConnectorServiceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ConnectorServiceDeleteCall) Return(arg0 error) *ConnectorServiceDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ConnectorServiceDeleteCall) Do(f func(context.Context, string, connector.PluginDispenserFetcher) error) *ConnectorServiceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ConnectorServiceDeleteCall) DoAndReturn(f func(context.Context, string, connector.PluginDispenserFetcher) error) *ConnectorServiceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *ConnectorService) Get(arg0 context.Context, arg1 string) (*connector.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*connector.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *ConnectorServiceMockRecorder) Get(arg0, arg1 any) *ConnectorServiceGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*ConnectorService)(nil).Get), arg0, arg1)
	return &ConnectorServiceGetCall{Call: call}
}

// ConnectorServiceGetCall wrap *gomock.Call
type ConnectorServiceGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ConnectorServiceGetCall) Return(arg0 *connector.Instance, arg1 error) *ConnectorServiceGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ConnectorServiceGetCall) Do(f func(context.Context, string) (*connector.Instance, error)) *ConnectorServiceGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ConnectorServiceGetCall) DoAndReturn(f func(context.Context, string) (*connector.Instance, error)) *ConnectorServiceGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemoveProcessor mocks base method.
func (m *ConnectorService) RemoveProcessor(arg0 context.Context, arg1, arg2 string) (*connector.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveProcessor", arg0, arg1, arg2)
	ret0, _ := ret[0].(*connector.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveProcessor indicates an expected call of RemoveProcessor.
func (mr *ConnectorServiceMockRecorder) RemoveProcessor(arg0, arg1, arg2 any) *ConnectorServiceRemoveProcessorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveProcessor", reflect.TypeOf((*ConnectorService)(nil).RemoveProcessor), arg0, arg1, arg2)
	return &ConnectorServiceRemoveProcessorCall{Call: call}
}

// ConnectorServiceRemoveProcessorCall wrap *gomock.Call
type ConnectorServiceRemoveProcessorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ConnectorServiceRemoveProcessorCall) Return(arg0 *connector.Instance, arg1 error) *ConnectorServiceRemoveProcessorCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ConnectorServiceRemoveProcessorCall) Do(f func(context.Context, string, string) (*connector.Instance, error)) *ConnectorServiceRemoveProcessorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ConnectorServiceRemoveProcessorCall) DoAndReturn(f func(context.Context, string, string) (*connector.Instance, error)) *ConnectorServiceRemoveProcessorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *ConnectorService) Update(arg0 context.Context, arg1 string, arg2 connector.Config) (*connector.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*connector.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *ConnectorServiceMockRecorder) Update(arg0, arg1, arg2 any) *ConnectorServiceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*ConnectorService)(nil).Update), arg0, arg1, arg2)
	return &ConnectorServiceUpdateCall{Call: call}
}

// ConnectorServiceUpdateCall wrap *gomock.Call
type ConnectorServiceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ConnectorServiceUpdateCall) Return(arg0 *connector.Instance, arg1 error) *ConnectorServiceUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ConnectorServiceUpdateCall) Do(f func(context.Context, string, connector.Config) (*connector.Instance, error)) *ConnectorServiceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ConnectorServiceUpdateCall) DoAndReturn(f func(context.Context, string, connector.Config) (*connector.Instance, error)) *ConnectorServiceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ProcessorService is a mock of ProcessorService interface.
type ProcessorService struct {
	ctrl     *gomock.Controller
	recorder *ProcessorServiceMockRecorder
}

// ProcessorServiceMockRecorder is the mock recorder for ProcessorService.
type ProcessorServiceMockRecorder struct {
	mock *ProcessorService
}

// NewProcessorService creates a new mock instance.
func NewProcessorService(ctrl *gomock.Controller) *ProcessorService {
	mock := &ProcessorService{ctrl: ctrl}
	mock.recorder = &ProcessorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ProcessorService) EXPECT() *ProcessorServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *ProcessorService) Create(arg0 context.Context, arg1, arg2 string, arg3 processor.Parent, arg4 processor.Config, arg5 processor.ProvisionType, arg6 string) (*processor.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(*processor.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *ProcessorServiceMockRecorder) Create(arg0, arg1, arg2, arg3, arg4, arg5, arg6 any) *ProcessorServiceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*ProcessorService)(nil).Create), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	return &ProcessorServiceCreateCall{Call: call}
}

// ProcessorServiceCreateCall wrap *gomock.Call
type ProcessorServiceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ProcessorServiceCreateCall) Return(arg0 *processor.Instance, arg1 error) *ProcessorServiceCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ProcessorServiceCreateCall) Do(f func(context.Context, string, string, processor.Parent, processor.Config, processor.ProvisionType, string) (*processor.Instance, error)) *ProcessorServiceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ProcessorServiceCreateCall) DoAndReturn(f func(context.Context, string, string, processor.Parent, processor.Config, processor.ProvisionType, string) (*processor.Instance, error)) *ProcessorServiceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *ProcessorService) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *ProcessorServiceMockRecorder) Delete(arg0, arg1 any) *ProcessorServiceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*ProcessorService)(nil).Delete), arg0, arg1)
	return &ProcessorServiceDeleteCall{Call: call}
}

// ProcessorServiceDeleteCall wrap *gomock.Call
type ProcessorServiceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ProcessorServiceDeleteCall) Return(arg0 error) *ProcessorServiceDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ProcessorServiceDeleteCall) Do(f func(context.Context, string) error) *ProcessorServiceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ProcessorServiceDeleteCall) DoAndReturn(f func(context.Context, string) error) *ProcessorServiceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *ProcessorService) Get(arg0 context.Context, arg1 string) (*processor.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*processor.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *ProcessorServiceMockRecorder) Get(arg0, arg1 any) *ProcessorServiceGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*ProcessorService)(nil).Get), arg0, arg1)
	return &ProcessorServiceGetCall{Call: call}
}

// ProcessorServiceGetCall wrap *gomock.Call
type ProcessorServiceGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ProcessorServiceGetCall) Return(arg0 *processor.Instance, arg1 error) *ProcessorServiceGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ProcessorServiceGetCall) Do(f func(context.Context, string) (*processor.Instance, error)) *ProcessorServiceGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ProcessorServiceGetCall) DoAndReturn(f func(context.Context, string) (*processor.Instance, error)) *ProcessorServiceGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MakeRunnableProcessor mocks base method.
func (m *ProcessorService) MakeRunnableProcessor(arg0 context.Context, arg1 *processor.Instance) (*processor.RunnableProcessor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeRunnableProcessor", arg0, arg1)
	ret0, _ := ret[0].(*processor.RunnableProcessor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeRunnableProcessor indicates an expected call of MakeRunnableProcessor.
func (mr *ProcessorServiceMockRecorder) MakeRunnableProcessor(arg0, arg1 any) *ProcessorServiceMakeRunnableProcessorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeRunnableProcessor", reflect.TypeOf((*ProcessorService)(nil).MakeRunnableProcessor), arg0, arg1)
	return &ProcessorServiceMakeRunnableProcessorCall{Call: call}
}

// ProcessorServiceMakeRunnableProcessorCall wrap *gomock.Call
type ProcessorServiceMakeRunnableProcessorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ProcessorServiceMakeRunnableProcessorCall) Return(arg0 *processor.RunnableProcessor, arg1 error) *ProcessorServiceMakeRunnableProcessorCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ProcessorServiceMakeRunnableProcessorCall) Do(f func(context.Context, *processor.Instance) (*processor.RunnableProcessor, error)) *ProcessorServiceMakeRunnableProcessorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ProcessorServiceMakeRunnableProcessorCall) DoAndReturn(f func(context.Context, *processor.Instance) (*processor.RunnableProcessor, error)) *ProcessorServiceMakeRunnableProcessorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *ProcessorService) Update(arg0 context.Context, arg1 string, arg2 processor.Config) (*processor.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*processor.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *ProcessorServiceMockRecorder) Update(arg0, arg1, arg2 any) *ProcessorServiceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*ProcessorService)(nil).Update), arg0, arg1, arg2)
	return &ProcessorServiceUpdateCall{Call: call}
}

// ProcessorServiceUpdateCall wrap *gomock.Call
type ProcessorServiceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ProcessorServiceUpdateCall) Return(arg0 *processor.Instance, arg1 error) *ProcessorServiceUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ProcessorServiceUpdateCall) Do(f func(context.Context, string, processor.Config) (*processor.Instance, error)) *ProcessorServiceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ProcessorServiceUpdateCall) DoAndReturn(f func(context.Context, string, processor.Config) (*processor.Instance, error)) *ProcessorServiceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ConnectorPluginService is a mock of ConnectorPluginService interface.
type ConnectorPluginService struct {
	ctrl     *gomock.Controller
	recorder *ConnectorPluginServiceMockRecorder
}

// ConnectorPluginServiceMockRecorder is the mock recorder for ConnectorPluginService.
type ConnectorPluginServiceMockRecorder struct {
	mock *ConnectorPluginService
}

// NewConnectorPluginService creates a new mock instance.
func NewConnectorPluginService(ctrl *gomock.Controller) *ConnectorPluginService {
	mock := &ConnectorPluginService{ctrl: ctrl}
	mock.recorder = &ConnectorPluginServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ConnectorPluginService) EXPECT() *ConnectorPluginServiceMockRecorder {
	return m.recorder
}

// NewDispenser mocks base method.
func (m *ConnectorPluginService) NewDispenser(arg0 log.CtxLogger, arg1, arg2 string) (connector0.Dispenser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewDispenser", arg0, arg1, arg2)
	ret0, _ := ret[0].(connector0.Dispenser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewDispenser indicates an expected call of NewDispenser.
func (mr *ConnectorPluginServiceMockRecorder) NewDispenser(arg0, arg1, arg2 any) *ConnectorPluginServiceNewDispenserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDispenser", reflect.TypeOf((*ConnectorPluginService)(nil).NewDispenser), arg0, arg1, arg2)
	return &ConnectorPluginServiceNewDispenserCall{Call: call}
}

// ConnectorPluginServiceNewDispenserCall wrap *gomock.Call
type ConnectorPluginServiceNewDispenserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ConnectorPluginServiceNewDispenserCall) Return(arg0 connector0.Dispenser, arg1 error) *ConnectorPluginServiceNewDispenserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ConnectorPluginServiceNewDispenserCall) Do(f func(log.CtxLogger, string, string) (connector0.Dispenser, error)) *ConnectorPluginServiceNewDispenserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ConnectorPluginServiceNewDispenserCall) DoAndReturn(f func(log.CtxLogger, string, string) (connector0.Dispenser, error)) *ConnectorPluginServiceNewDispenserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
