// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package impl

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	cloneConfigCount = "count"
)

func (cloneConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		cloneConfigCount: {
			Default:     "",
			Description: "The number of records after cloning (e.g. if count is 3, the processor\nwill output 3 records for every input record).",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{
				config.ValidationRequired{},
				config.ValidationGreaterThan{V: 1},
			},
		},
	}
}
