// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package impl

import (
	"github.com/conduitio/conduit-commons/config"
)

func (errorConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		"message": {
			Default:     "error processor triggered",
			Description: "Error message to be returned. This can be a Go [template](https://pkg.go.dev/text/template)\nexecuted on each [`Record`](https://pkg.go.dev/github.com/conduitio/conduit-commons/opencdc#Record)\nbeing processed.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
	}
}
