// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package impl

import (
	"regexp"

	"github.com/conduitio/conduit-commons/config"
)

const (
	splitConfigField = "field"
)

func (splitConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		splitConfigField: {
			Default:     "",
			Description: "Field is the target field that should be split. Note that the target\nfield has to contain an array so it can be split. This also means you can\nonly split on fields in structured data under `.Key` and `.Payload`.\n\nFor more information about the format, see [Referencing fields](https://conduit.io/docs/using/processors/referencing-fields).",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
				config.ValidationRegex{Regex: regexp.MustCompile("^\\.(Payload|Key).*")},
			},
		},
	}
}
