// Copyright © 2026 Meroxa, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package index

import (
	"crypto/ed25519"
	"crypto/sha256"
	"crypto/x509"
	"encoding/hex"

	"github.com/conduitio/conduit/pkg/foundation/cerrors"
)

// TrustAnchors holds the build-time-fixed root and freshness public keys
// compiled into the conduit binary (R-1 OQ1/OQ2 resolution: trust anchors
// are fixed at build time and are NEVER updated at runtime — there is no
// runtime-fetched rotation statement, which would let a compromised old key
// forge a rotation to an attacker key).
//
// The production key material was generated by the bootstrap ceremony
// (plan-v2 §9) and is go:embed'd into the binary at
// cmd/conduit/root/connectors/trustanchors/{root,freshness}.pub.pem; a
// released build verifies the served signed index at
// https://registry.conduitdata.io/index.json against it. This type itself is
// generic — a build with no embedded anchors (a custom or stripped build)
// leaves it empty, and every real index then fails closed with
// CodeTrustAnchorExpired (never fail-open).
type TrustAnchors struct {
	// Roots holds every currently-trusted root public key, keyed by keyId
	// (e.g. "sha256:<hex fingerprint of the SPKI-encoded public key>").
	// During a rotation window both the outgoing and incoming root key are
	// present simultaneously (R-1 OQ2) for a retention window tracking
	// Conduit's supported-version policy.
	Roots map[string]ed25519.PublicKey
	// Freshness holds the currently-trusted freshness public key(s), keyed
	// by keyId. A freshness signature may only extend index.timestamp/bump
	// index.version over byte-identical connectors[]; it never authorizes
	// content on its own (R-1 OQ3).
	Freshness map[string]ed25519.PublicKey
}

// KeyID returns the anchor keyId this package uses for an ed25519 public key:
// "sha256:<hex fingerprint of the SPKI-encoded public key>" (see TrustAnchors'
// doc comment). Both the index-build/signing tooling (a sibling repo, per
// plan-v2 §7) and this package's tests must derive keyIds identically — this
// is that single shared derivation, exported so test fixtures and (via the
// pinned module import, plan-v2 §2.5) index-CI tooling never hand-roll their
// own and risk drifting from what Verify actually expects.
func KeyID(pub ed25519.PublicKey) (string, error) {
	spki, err := x509.MarshalPKIXPublicKey(pub)
	if err != nil {
		return "", cerrors.Errorf("could not marshal ed25519 public key to SPKI: %w", err)
	}
	sum := sha256.Sum256(spki)
	return "sha256:" + hex.EncodeToString(sum[:]), nil
}
