version: 1.0
pipelines:
  file-to-file:
    status: running
    description: >
      Example pipeline reading from file "example.in" and writing into file
      "example.out". Note that the output file will contain the whole OpenCDC
      record, the field "payload.after" will contain the base64 encoded line
      written in "example.in".
    connectors:
      example.in:
        type: source
        plugin: builtin:file
        settings:
          path: ./example.in
      example.out:
        type: destination
        plugin: builtin:file
        settings:
          path: ./example.out
