version: 2.2
pipelines:
  - id: add-department
    status: running
    description: >
      An example pipeline which reads data (imaginary employees) from two generator
      sources, processes it and writes it to a file.
      
      It attaches the built-in `field.set` processor to one of the sources
      to add a `department` field to its records. The records from the other source
      are not processed.
    connectors:
      - id: employees-1
        type: source
        plugin: builtin:generator
        settings:
          format.type: "structured"
          format.options.id: int
          format.options.name: string
          format.options.company: string
          format.options.trial: bool
          recordCount: "1"
        processors:
          - id: extract-name
            plugin: field.set
            settings:
              field: '.Payload.After.department'
              value: 'finance'
      - id: employees-2
        type: source
        plugin: builtin:generator
        settings:
          format.type: "structured"
          format.options.id: int
          format.options.name: string
          format.options.company: string
          format.options.trial: bool
          recordCount: "2"
      - id: file-destination
        type: destination
        plugin: builtin:file
        settings:
          path: ./example.out