// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package builtin

import (
	"github.com/conduitio/conduit-commons/config"
)

func (excludeFieldConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		"fields": {
			Default:     "",
			Description: "fields to be excluded from the record, as it would be addressed in a Go template, as a comma separated list.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
