name: buf

on:
  push:
    branches:
      - main
    paths:
      - 'proto/**'
  pull_request:
    paths:
      - 'proto/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          input: 'proto'
          push: false
          breaking_against: '${{ github.event.repository.clone_url }}#branch=main,subdir=proto'

  # Push buf module to the buf schema registry, but only if the validate action succeeded and if the action is running
  # on branch main.
  push:
    runs-on: ubuntu-latest
    needs: validate
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          input: 'proto'
