name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Generated files
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make install-tools
          make generate
          git diff --exit-code --numstat

      - name: Test
        run: make test-integration GOTEST_FLAGS="-v -count=1"
