name: project-management

on:
  issues:
    types: [opened]

jobs:
  project-mgmt:
    uses: ConduitIO/automation/.github/workflows/project-automation.yml@main
    secrets:
      project-automation-token: ${{ secrets.PROJECT_AUTOMATION }}
