name: public-roadmap

on:
  issues:
    types: [demilestoned, milestoned]

jobs:
  add_to_public_roadmap:
    runs-on: unbuntu-latest
    if: github.issues.event == 'milestoned'
    steps:
      - name: Fetch project data
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_AUTOMATION }}
          ORGANIZATION: ConduitIO
          PROJECT_NUMBER: 3
        run: |
          gh api graphql -f query='
            query($org: String!, $number: Int!) {
              organization(login: $org){
                projectNext(number: $number) {
                  id
                  fields(first:20) {
                    nodes {
                      id
                      name
                      settings
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION -F number=$PROJECT_NUMBER > project_data.json

      # note that if the item was already on the roadmap we'll
      # get an error from the api. that's ok.
      - name: Add to Roadmap
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_AUTOMATION }}
          ISSUE_ID: ${{ github.event.issue.node_id }}
        run: |
          item_id="$( gh api graphql -f query='
            mutation($project:ID!, $pr:ID!) {
              addProjectNextItem(input: {projectId: $project, contentId: $pr}) {
                projectNextItem {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f pr=$PR_ID --jq '.data.addProjectNextItem.projectNextItem.id')"
