name: public-roadmap

on:
  issues:
    types: [demilestoned, milestoned]

jobs:
  add_to_public_roadmap:
    runs-on: ubuntu-latest
    if: github.event.action == 'milestoned'
    steps:
      # note that if the item was already on the roadmap we
      # get an error from the api. that's ok.
      - name: Add to Roadmap
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_AUTOMATION }}
          ISSUE_ID: ${{ github.event.issue.node_id }}
          PROJECT_ID: PN_kwDOBL3ZPs4AAigJ
        run: |
          item_id="$( gh api graphql -f query='
            mutation($project:ID!, $issue:ID!) {
              addProjectNextItem(input: {projectId: $project, contentId: $issue}) {
                projectNextItem {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f issue=$ISSUE_ID --jq '.data.addProjectNextItem.projectNextItem.id')"


  remove_from_public_roadmap:
    runs-on: ubuntu-latest
    # only remove if the milestone is null. If you change between milestones
    # github will include the demilestoned event.
    if: github.event.action == 'demilestoned' && github.event.issue.milestone == ''
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set Node Version
        uses: actions/setup-node@v1
        with:
          node-version: '16'
          cache: 'npm'

      - name: Delete item from public roadmap
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_AUTOMATION }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          PROJECT_ID: PN_kwDOBL3ZPs4AAigJ
          ISSUE_ID: ${{ github.event.issue.node_id }}
        working-directory: ./.github/actions/
        run: |
          npm install
          npm run roadmap

