name: UI tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
    paths:
      - 'ui/**'
  pull_request:
    branches:
      - main
    paths:
      - 'ui/**'

jobs:
  test-app:
    name: Running Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: make ui-dependencies

      - name: ember t
        run: make ui-test
